### ISSUE TITLE
'package' doesn't match hashsum => 'hashsum', clean the cache and try again

### ISSUE THREAD

**Issue by AwlsomeAlex** [minos-org/minos-static#10] opened 2017-07-03 18:44 UTC
Hello, I'm currently experimenting with static-get on a minimal system with nothing but busybox and network support but whenever I go to install the package 'nano', I just get an error for an incorrect hashsum. I've even tried to clear the cache by `./static-get.sh -c` and it could say the cache is cleared but when I try to install it again with `./static-get.sh nano` I would just get that error. 

[Terminal Output:](https://ibb.co/d2aSPa)

Thanks! I also tried with the current static-get script and the http://s.minos.io/s download but both give same error.

**Comment by javier-lopez** [comment] 2017-07-03 18:49
Hello @AwlsomeAlex ,

I'm sorry for the issue, could you try to execute the script in debugging mode after clearing the cache?

    $ sh -x static-get.sh -c
    $ sh -x static-get.sh nano

Also, if you could provide more information about the target environment I could try to replicate it.

**Comment by AwlsomeAlex** [comment] 2017-07-04 13:07
@javier-lopez I tried running it in debugging mode but it still didn't work. I'll provide the Debug Outputs Below. The environment is a bit difficult to explain, its a custom one that isn't based off of ANY Linux Distribution (The closest you could call it is LFS), it's only a simple GlibC 2.25, BusyBox 1.26.2 + Networking + Script Init, GRUB2, and Linux Kernel 4.9.35 environment I call StarLinux. If you want I can provide a Virtual Disk Image if that would make it easier.

[Cache Output](http://textuploader.com/dkkop)
[Nano Output](http://textuploader.com/dkkox)

**Comment by javier-lopez** [comment] 2017-07-04 20:24
@AwlsomeAlex thank you for the debugging output, it seems like the issue is with the `wget` version integrated into your busybox binary, please run the following commands in your target environment and attach the result.

    /bin/sh
    wget s.minos.io/archive/rlsd2/x86_64/nano.tar.xz
    echo $?
    md5sum nano.tar.xz

**Comment by AwlsomeAlex** [comment] 2017-07-04 20:27
@javier-lopez You were absolutely right. I tried the latest unstable version of BusyBox (1.27.0) and there was no problem at all!

Question: What do I do after I download and extract a package, lets say 'nano'. Like how do I then install it to the system?

**Comment by javier-lopez** [comment] 2017-07-04 20:53
@AwlsomeAlex you can launch it directly or move it to `/usr/bin` or other global PATH to make it available to all users; eg:

    $ ./static-get.sh -x nano
    nano.tar.xz
    nano/
    $ TERMINFO=/usr/share/terminfo/ ./nano/bin/nano

The **TERMINFO** variable is required because nano is a ncurses application, other commands don't require it, the above example uses the location where the TERMINFO database is located in an Ubuntu system.

PD: If you provide the wget output for your original busybox version I could fix static-get for such case.

**Comment by AwlsomeAlex** [comment] 2017-07-04 20:59
Sure, with the previous environment (1.26.2) I got this:
[Output](https://ibb.co/ew4WHv)

**Comment by AwlsomeAlex** [comment] 2017-07-04 21:26
@javier-lopez I plan on implementing static-get as a package manager for my linux distribution. One addition that would be amazing is a way to install it onto the system. I mean it's simple enough to use it as the static packages but for now I'll be writing a script that'll use static-get to install and extract the packages but the rest of the script will install it.

**Comment by javier-lopez** [comment] 2017-07-04 21:50
Cool!, when implementing the installation phase be aware than the location vary from package to package, some are under `$package/bin`, while others use `$package/usr/bin`, etc. This is because `static-get` is a compilation of [several](https://github.com/jelaas/bifrost-build) [upstream](http://git.2f30.org/ports/) [distros](https://github.com/dimkr/rlsd2) with different policies about the default installation path.

**Comment by AwlsomeAlex** [comment] 2017-07-04 21:51
@javier-lopez Okay, thanks alot for your help!

**Comment by javier-lopez** [comment] 2017-07-05 00:42
I've replicated the error with busybox 1.26.2, according to https://bugs.busybox.net/show_bug.cgi?id=9471 it's due to a broken http server (on this case nginx), I disagree, I think the problem lies on this specific busybox version.

The mentioned busybox version _closes_ its writing side upon sending its request (like common DDOS tools), nginx and the like think "this guy looks like an attacker (even though its request is technically valid, browsers don't do that (they use persistent connections, for one))" and drops the connection.

Since the used nginx version works with most fetchers, including curl, fetch, gnu wget and common browsers I'm marking this problem as won't fix (a solution could be to replace the http server at s.minos.io with one who don't closes the connection when the client behave like a DDOS tool). I suggest avoiding  busybox 1.26.2.

Feel free to open new issues.

**Closed as completed by javier-lopez** 2017-07-05 00:42 UTC
Labels: wontfix
